### ISSUE TITLE
Webserver-Demo baut nicht

### ISSUE THREAD

**Issue by shagedorn** [cocoaheads-dd/presentations#6]
Die [Webserver](https://github.com/cocoaheads-dd/presentations/tree/master/Swift%20Open%20Source/Webserver)-Demo baut bei mir nicht (`swift build` mit der Dev-Toolchain von swift.org). OS X 10.11.

U.a.
`Compiling Swift Module 'Core' (15 sources)
~/Documents/Projects/presentations/Swift Open Source/Webserver/Packages/CURIParser-0.1.0/module.modulemap:2:12: error: header '/usr/local/include/uri_parser/uri_parser.h' not found
    header "/usr/local/include/uri_parser/uri_parser.h"`

...uvm. (sehr ähnlich).

**Comment by kiliankoe** [comment]
[Epoch](https://github.com/zewo/epoch) ist leider nicht komplett alles, selbst hat es noch ein paar externe Dependencies. Ist nicht so ganz ideal :/

aus der Readme:
```
$ brew tap zewo/tap
$ brew install libvenice http_parser uri_parser
```

**Comment by shagedorn** [comment]
Alles klar. Vielleicht wäre dann eine Readme (hier) im Webserver-Ordner noch hilfreich. Komm am WE vermutlich nicht dazu, mach das im Zweifel am Montag.

**Comment by BenchR267** [comment]
Gute Idee, füge ich heute noch hinzu

**Comment by BenchR267** [comment]
Done in 7b429854b9a2a84244c1f6b5b0ee3dc792303fee
